version: '2'
services:
    web:
        container_name: web
        build: .
        volumes:
            - .:/app
        expose:
            - 5000
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:8080"
        expose:
            - 8080
