apiVersion: batch/v1
kind: Job
metadata:
  name: vrt-metadata-updater
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: vrt-metadata-updater
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/vrt-metadata-updater/vrt-metadata-updater:latest
          imagePullPolicy: Always
          name: vrt-metadata-updater
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/src/app/config.yml
              name: vrtmetadataupdater-config
              readOnly: true
              subPath: config.yml
      restartPolicy: Never
      volumes:
        - configMap:
            defaultMode: 420
            name: vrtmetadataupdater-config
          name: vrtmetadataupdater-config
